name: local_storage_theme_api
description: Implementacion para el almacenamiento local del tema de la aplicacion
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  theme_api:
    path: ../theme_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
