name: users_api
description: Interfaz y Modelo para el API de los usuarios
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.11.0
  uuid: ^4.3.3
